"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert("modells", [
      {
        name: "Corolla",
        brand_id: 1,
        year: 2024,
        engine_type: "Inline-4",
        fuel_type: "Petrol",
        transmission: "Automatic",
        color_options: JSON.stringify(["White", "Black", "Silver"]),
        description:
          "A compact and efficient car, popular for its reliability.",
        status: "active",
        is_delete: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Camry",
        brand_id: 1,
        year: 2024,
        engine_type: "Inline-4",
        fuel_type: "Hybrid",
        transmission: "Automatic",
        color_options: JSON.stringify(["Blue", "Red", "White"]),
        description:
          "A mid-size sedan with luxury features and great fuel economy.",
        status: "active",
        is_delete: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Hilux",
        brand_id: 1,
        year: 2024,
        engine_type: "Inline-4",
        fuel_type: "Diesel",
        transmission: "Manual",
        color_options: JSON.stringify(["Black", "Silver", "Green"]),
        description:
          "A robust and durable pickup truck for both work and leisure.",
        status: "active",
        is_delete: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Fortuner",
        brand_id: 1,
        year: 2024,
        engine_type: "V6",
        fuel_type: "Diesel",
        transmission: "Automatic",
        color_options: JSON.stringify(["Black", "Grey", "White"]),
        description:
          "A powerful SUV with ample space for family and off-road adventures.",
        status: "active",
        is_delete: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Land Cruiser",
        brand_id: 1,
        year: 2024,
        engine_type: "V8",
        fuel_type: "Diesel",
        transmission: "Automatic",
        color_options: JSON.stringify(["Silver", "White", "Black"]),
        description: "A legendary off-road vehicle with unmatched durability.",
        status: "active",
        is_delete: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // Models for Harley-Davidson (brand_id: 2)
      {
        name: "Street 750",
        brand_id: 2,
        year: 2024,
        engine_type: "V-Twin",
        fuel_type: "Petrol",
        transmission: "Manual",
        color_options: JSON.stringify(["Black", "Red", "Silver"]),
        description: "A light cruiser motorcycle designed for the streets.",
        status: "active",
        is_delete: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Iron 883",
        brand_id: 2,
        year: 2024,
        engine_type: "V-Twin",
        fuel_type: "Petrol",
        transmission: "Manual",
        color_options: JSON.stringify(["Black", "Blue", "Silver"]),
        description: "A minimalist bike with a retro look and feel.",
        status: "active",
        is_delete: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Sportster S",
        brand_id: 2,
        year: 2024,
        engine_type: "V-Twin",
        fuel_type: "Petrol",
        transmission: "Manual",
        color_options: JSON.stringify(["Black", "Matte Grey"]),
        description:
          "A sport-oriented motorcycle with exceptional performance.",
        status: "active",
        is_delete: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Fat Boy",
        brand_id: 2,
        year: 2024,
        engine_type: "V-Twin",
        fuel_type: "Petrol",
        transmission: "Manual",
        color_options: JSON.stringify(["Black", "Silver", "Chrome"]),
        description: "A classic heavyweight cruiser with timeless design.",
        status: "active",
        is_delete: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Road King",
        brand_id: 2,
        year: 2024,
        engine_type: "V-Twin",
        fuel_type: "Petrol",
        transmission: "Manual",
        color_options: JSON.stringify(["Black", "Red", "Blue"]),
        description:
          "A touring motorcycle with advanced features for long-distance rides.",
        status: "active",
        is_delete: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // Models for Yamaha (brand_id: 3)
      {
        name: "YZF-R1",
        brand_id: 3,
        year: 2024,
        engine_type: "Inline-4",
        fuel_type: "Petrol",
        transmission: "Manual",
        color_options: JSON.stringify(["Blue", "Black", "White"]),
        description: "A superbike with extreme performance and agility.",
        status: "active",
        is_delete: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "MT-09",
        brand_id: 3,
        year: 2024,
        engine_type: "Inline-3",
        fuel_type: "Petrol",
        transmission: "Manual",
        color_options: JSON.stringify(["Black", "Orange", "Grey"]),
        description: "A naked bike with strong torque and an aggressive look.",
        status: "active",
        is_delete: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "FZ-07",
        brand_id: 3,
        year: 2024,
        engine_type: "Parallel-Twin",
        fuel_type: "Petrol",
        transmission: "Manual",
        color_options: JSON.stringify(["Black", "Red", "White"]),
        description: "A lightweight street bike that’s perfect for beginners.",
        status: "active",
        is_delete: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "VMAX",
        brand_id: 3,
        year: 2024,
        engine_type: "V4",
        fuel_type: "Petrol",
        transmission: "Manual",
        color_options: JSON.stringify(["Silver", "Black", "Red"]),
        description: "A muscle bike with raw power and brutal performance.",
        status: "active",
        is_delete: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "FZ-09",
        brand_id: 3,
        year: 2024,
        engine_type: "Inline-3",
        fuel_type: "Petrol",
        transmission: "Manual",
        color_options: JSON.stringify(["Black", "Yellow", "Blue"]),
        description: "A dynamic and agile street bike with great handling.",
        status: "active",
        is_delete: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // Models for Ducati (brand_id: 4)
      {
        name: "Panigale V4",
        brand_id: 4,
        year: 2024,
        engine_type: "V4",
        fuel_type: "Petrol",
        transmission: "Manual",
        color_options: JSON.stringify(["Red", "Black", "White"]),
        description:
          "A high-performance sportbike with track-ready capabilities.",
        status: "active",
        is_delete: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Monster",
        brand_id: 4,
        year: 2024,
        engine_type: "V-Twin",
        fuel_type: "Petrol",
        transmission: "Manual",
        color_options: JSON.stringify(["Yellow", "Red", "Black"]),
        description:
          "A naked bike with raw Ducati performance and iconic design.",
        status: "active",
        is_delete: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Scrambler",
        brand_id: 4,
        year: 2024,
        engine_type: "L-Twin",
        fuel_type: "Petrol",
        transmission: "Manual",
        color_options: JSON.stringify(["Yellow", "Orange", "Black"]),
        description:
          "A fun and versatile bike designed for both on and off-road adventures.",
        status: "active",
        is_delete: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Diavel",
        brand_id: 4,
        year: 2024,
        engine_type: "V-Twin",
        fuel_type: "Petrol",
        transmission: "Manual",
        color_options: JSON.stringify(["Black", "Red", "Grey"]),
        description:
          "A power cruiser combining Ducati’s sports performance with cruising comfort.",
        status: "active",
        is_delete: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Multistrada V4",
        brand_id: 4,
        year: 2024,
        engine_type: "V4",
        fuel_type: "Petrol",
        transmission: "Automatic",
        color_options: JSON.stringify(["Red", "Black", "White"]),
        description:
          "An adventure touring bike with all-road versatility and cutting-edge technology.",
        status: "active",
        is_delete: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // Models for BMW (brand_id: 5)
      {
        name: "BMW X5",
        brand_id: 5,
        year: 2024,
        engine_type: "Inline-6",
        fuel_type: "Petrol",
        transmission: "Automatic",
        color_options: JSON.stringify(["Black", "White", "Silver", "Blue"]),
        description:
          "A luxury SUV with premium features, off-road capability, and powerful performance.",
        status: "active",
        is_delete: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "BMW 3 Series",
        brand_id: 5,
        year: 2024,
        engine_type: "Inline-4",
        fuel_type: "Petrol",
        transmission: "Automatic",
        color_options: JSON.stringify(["White", "Black", "Silver", "Grey"]),
        description:
          "A sporty compact sedan that blends luxury and performance with agile handling.",
        status: "active",
        is_delete: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "BMW M5",
        brand_id: 5,
        year: 2024,
        engine_type: "V8",
        fuel_type: "Petrol",
        transmission: "Automatic",
        color_options: JSON.stringify(["Black", "Blue", "Silver", "Red"]),
        description:
          "A high-performance sedan with an aggressive engine and advanced driving dynamics.",
        status: "active",
        is_delete: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "BMW Z4",
        brand_id: 5,
        year: 2024,
        engine_type: "Inline-6",
        fuel_type: "Petrol",
        transmission: "Automatic",
        color_options: JSON.stringify(["Red", "White", "Black", "Yellow"]),
        description:
          "A two-door sports car with sharp handling and a powerful engine, perfect for driving enthusiasts.",
        status: "active",
        is_delete: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "BMW 7 Series",
        brand_id: 5,
        year: 2024,
        engine_type: "Inline-6",
        fuel_type: "Petrol",
        transmission: "Automatic",
        color_options: JSON.stringify(["Black", "Silver", "Blue", "White"]),
        description:
          "A flagship luxury sedan with advanced tech, comfort, and a refined driving experience.",
        status: "active",
        is_delete: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // Models for Honda (brand_id: 6)
      {
        name: "Civic",
        brand_id: 6,
        year: 2024,
        engine_type: "Inline-4",
        fuel_type: "Petrol",
        transmission: "Automatic",
        color_options: JSON.stringify(["White", "Black", "Silver", "Blue"]),
        description:
          "A compact sedan with a reputation for reliability, efficiency, and sporty handling.",
        status: "active",
        is_delete: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Accord",
        brand_id: 6,
        year: 2024,
        engine_type: "Inline-4",
        fuel_type: "Petrol",
        transmission: "Automatic",
        color_options: JSON.stringify(["Silver", "Black", "White", "Red"]),
        description:
          "A midsize sedan offering a balance of comfort, technology, and performance.",
        status: "active",
        is_delete: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "CR-V",
        brand_id: 6,
        year: 2024,
        engine_type: "Inline-4",
        fuel_type: "Petrol",
        transmission: "Automatic",
        color_options: JSON.stringify(["White", "Black", "Blue", "Grey"]),
        description:
          "A popular compact SUV known for its practicality, comfort, and fuel efficiency.",
        status: "active",
        is_delete: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Pilot",
        brand_id: 6,
        year: 2024,
        engine_type: "V6",
        fuel_type: "Petrol",
        transmission: "Automatic",
        color_options: JSON.stringify(["Black", "White", "Silver", "Red"]),
        description:
          "A spacious 3-row SUV designed for families, with ample cargo space and advanced safety features.",
        status: "active",
        is_delete: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "CBR600RR",
        brand_id: 6,
        year: 2024,
        engine_type: "Inline-4",
        fuel_type: "Petrol",
        transmission: "Manual",
        color_options: JSON.stringify(["Red", "Black", "White", "Blue"]),
        description:
          "A high-performance sportbike designed for sharp handling, agility, and track use.",
        status: "active",
        is_delete: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      {
        name: "Mustang",
        brand_id: 7,
        year: 2024,
        engine_type: "V8",
        fuel_type: "Petrol",
        transmission: "Manual",
        color_options: JSON.stringify(["Red", "Black", "Blue", "Silver"]),
        description:
          "An iconic muscle car known for its powerful performance and aggressive styling.",
        status: "active",
        is_delete: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "F-150",
        brand_id: 7,
        year: 2024,
        engine_type: "V6",
        fuel_type: "Petrol",
        transmission: "Automatic",
        color_options: JSON.stringify(["White", "Black", "Blue", "Silver"]),
        description:
          "A rugged and durable full-size pickup truck designed for work and play.",
        status: "active",
        is_delete: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Explorer",
        brand_id: 7,
        year: 2024,
        engine_type: "Inline-4",
        fuel_type: "Petrol",
        transmission: "Automatic",
        color_options: JSON.stringify(["White", "Black", "Grey", "Silver"]),
        description:
          "A midsize SUV that combines family-friendly features with off-road capability.",
        status: "active",
        is_delete: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Focus",
        brand_id: 7,
        year: 2024,
        engine_type: "Inline-4",
        fuel_type: "Petrol",
        transmission: "Automatic",
        color_options: JSON.stringify(["Red", "Blue", "White", "Black"]),
        description:
          "A compact car that offers an engaging driving experience and excellent fuel efficiency.",
        status: "active",
        is_delete: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Ranger",
        brand_id: 7,
        year: 2024,
        engine_type: "V6",
        fuel_type: "Petrol",
        transmission: "Automatic",
        color_options: JSON.stringify(["White", "Blue", "Black", "Red"]),
        description:
          "A midsize pickup truck designed for both work and recreation, with rugged capability.",
        status: "active",
        is_delete: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // Suzuki (brand_id: 8)
      {
        name: "Swift",
        brand_id: 8,
        year: 2024,
        engine_type: "Inline-4",
        fuel_type: "Petrol",
        transmission: "Automatic",
        color_options: JSON.stringify(["Red", "White", "Black", "Silver"]),
        description:
          "A compact hatchback known for its fuel efficiency, agility, and fun driving experience.",
        status: "active",
        is_delete: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Vitara",
        brand_id: 8,
        year: 2024,
        engine_type: "Inline-4",
        fuel_type: "Petrol",
        transmission: "Automatic",
        color_options: JSON.stringify(["White", "Black", "Grey", "Silver"]),
        description:
          "A small crossover SUV that offers versatility and all-wheel drive options.",
        status: "active",
        is_delete: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Baleno",
        brand_id: 8,
        year: 2024,
        engine_type: "Inline-4",
        fuel_type: "Petrol",
        transmission: "Automatic",
        color_options: JSON.stringify(["Blue", "White", "Black", "Red"]),
        description:
          "A compact sedan offering a smooth ride, efficient engine, and advanced safety features.",
        status: "active",
        is_delete: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Alto",
        brand_id: 8,
        year: 2024,
        engine_type: "Inline-3",
        fuel_type: "Petrol",
        transmission: "Manual",
        color_options: JSON.stringify(["White", "Red", "Silver", "Blue"]),
        description:
          "A small city car known for its compact size, affordability, and excellent fuel economy.",
        status: "active",
        is_delete: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "SX4",
        brand_id: 8,
        year: 2024,
        engine_type: "Inline-4",
        fuel_type: "Petrol",
        transmission: "Automatic",
        color_options: JSON.stringify(["Black", "Silver", "Red", "White"]),
        description:
          "A compact crossover combining the best of both hatchback and SUV designs.",
        status: "active",
        is_delete: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // Kawasaki (brand_id: 9)
      {
        name: "Ninja 650",
        brand_id: 9,
        year: 2024,
        engine_type: "Parallel Twin",
        fuel_type: "Petrol",
        transmission: "Manual",
        color_options: JSON.stringify(["Green", "Black", "White", "Blue"]),
        description:
          "A sportbike offering great balance of power, agility, and comfort for both beginners and experienced riders.",
        status: "active",
        is_delete: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Z900",
        brand_id: 9,
        year: 2024,
        engine_type: "Inline-4",
        fuel_type: "Petrol",
        transmission: "Manual",
        color_options: JSON.stringify(["Black", "Green", "Silver", "White"]),
        description:
          "A naked bike with a powerful engine, aggressive styling, and exceptional handling for experienced riders.",
        status: "active",
        is_delete: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Versys 650",
        brand_id: 9,
        year: 2024,
        engine_type: "Parallel Twin",
        fuel_type: "Petrol",
        transmission: "Manual",
        color_options: JSON.stringify(["Green", "Black", "Silver", "White"]),
        description:
          "A versatile adventure touring bike designed for long-distance riding and off-road capabilities.",
        status: "active",
        is_delete: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "KLR 650",
        brand_id: 9,
        year: 2024,
        engine_type: "Single-Cylinder",
        fuel_type: "Petrol",
        transmission: "Manual",
        color_options: JSON.stringify(["Green", "Black", "White"]),
        description:
          "An adventure bike perfect for off-road trails, commuting, and long-distance touring with a rugged design.",
        status: "active",
        is_delete: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Vulcan S",
        brand_id: 9,
        year: 2024,
        engine_type: "Parallel Twin",
        fuel_type: "Petrol",
        transmission: "Manual",
        color_options: JSON.stringify(["Black", "Silver", "Green", "Blue"]),
        description:
          "A cruiser-style motorcycle designed for riders of all sizes, with a customizable fit and smooth handling.",
        status: "active",
        is_delete: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // Mercedes-Benz (brand_id: 10)
      {
        name: "A-Class",
        brand_id: 10,
        year: 2024,
        engine_type: "Inline-4",
        fuel_type: "Petrol",
        transmission: "Automatic",
        color_options: JSON.stringify(["White", "Black", "Silver", "Blue"]),
        description:
          "A compact luxury hatchback with a stylish design, advanced technology, and excellent driving dynamics.",
        status: "active",
        is_delete: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "C-Class",
        brand_id: 10,
        year: 2024,
        engine_type: "Inline-4",
        fuel_type: "Petrol",
        transmission: "Automatic",
        color_options: JSON.stringify(["White", "Black", "Silver", "Red"]),
        description:
          "A luxury compact sedan offering a refined driving experience, exceptional comfort, and performance.",
        status: "active",
        is_delete: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "S-Class",
        brand_id: 10,
        year: 2024,
        engine_type: "V6",
        fuel_type: "Petrol",
        transmission: "Automatic",
        color_options: JSON.stringify(["Black", "White", "Silver", "Blue"]),
        description:
          "A full-size luxury sedan known for its premium features, advanced technology, and outstanding comfort.",
        status: "active",
        is_delete: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "E-Class",
        brand_id: 10,
        year: 2024,
        engine_type: "Inline-4",
        fuel_type: "Petrol",
        transmission: "Automatic",
        color_options: JSON.stringify(["White", "Silver", "Black", "Grey"]),
        description:
          "A midsize luxury sedan that blends performance, safety, and technology, offering a balanced driving experience.",
        status: "active",
        is_delete: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "GLA",
        brand_id: 10,
        year: 2024,
        engine_type: "Inline-4",
        fuel_type: "Petrol",
        transmission: "Automatic",
        color_options: JSON.stringify(["Black", "White", "Silver", "Red"]),
        description:
          "A luxury compact SUV with a sleek design, advanced safety features, and a dynamic driving experience.",
        status: "active",
        is_delete: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // Nissan (brand_id: 11)
      {
        name: "Altima",
        brand_id: 11,
        year: 2024,
        engine_type: "Inline-4",
        fuel_type: "Petrol",
        transmission: "Automatic",
        color_options: JSON.stringify(["White", "Silver", "Black", "Red"]),
        description:
          "A mid-size sedan offering a smooth ride, advanced safety features, and modern tech.",
        status: "active",
        is_delete: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Maxima",
        brand_id: 11,
        year: 2024,
        engine_type: "V6",
        fuel_type: "Petrol",
        transmission: "Automatic",
        color_options: JSON.stringify(["Black", "Silver", "White", "Blue"]),
        description:
          "A full-size sedan that delivers a premium driving experience, sporty handling, and high-tech features.",
        status: "active",
        is_delete: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Leaf",
        brand_id: 11,
        year: 2024,
        engine_type: "Electric",
        fuel_type: "Electric",
        transmission: "Automatic",
        color_options: JSON.stringify(["White", "Silver", "Blue", "Black"]),
        description:
          "An all-electric vehicle that combines eco-friendliness with practical features and comfort.",
        status: "active",
        is_delete: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "X-Trail",
        brand_id: 11,
        year: 2024,
        engine_type: "Inline-4",
        fuel_type: "Petrol",
        transmission: "Automatic",
        color_options: JSON.stringify(["Black", "Silver", "White", "Red"]),
        description:
          "A compact SUV with a strong performance, advanced safety systems, and a spacious interior.",
        status: "active",
        is_delete: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Navara",
        brand_id: 11,
        year: 2024,
        engine_type: "Inline-4",
        fuel_type: "Diesel",
        transmission: "Manual",
        color_options: JSON.stringify(["White", "Silver", "Black", "Grey"]),
        description:
          "A rugged pickup truck built for tough tasks, off-road capability, and towing power.",
        status: "active",
        is_delete: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // Harley-Davidson (brand_id: 12)
      {
        name: "Street 750",
        brand_id: 12,
        year: 2024,
        engine_type: "V-Twin",
        fuel_type: "Petrol",
        transmission: "Manual",
        color_options: JSON.stringify(["Black", "Red", "Silver", "Blue"]),
        description:
          "A cruiser-style motorcycle designed for urban commuting with a smooth ride and stylish looks.",
        status: "active",
        is_delete: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Iron 883",
        brand_id: 12,
        year: 2024,
        engine_type: "V-Twin",
        fuel_type: "Petrol",
        transmission: "Manual",
        color_options: JSON.stringify(["Black", "Grey", "White"]),
        description:
          "A classic Harley-Davidson cruiser with an iconic design, low profile, and powerful engine.",
        status: "active",
        is_delete: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Sportster S",
        brand_id: 12,
        year: 2024,
        engine_type: "V-Twin",
        fuel_type: "Petrol",
        transmission: "Manual",
        color_options: JSON.stringify(["Black", "Silver", "Red"]),
        description:
          "A modern take on the Sportster with advanced tech, aggressive styling, and a high-performance engine.",
        status: "active",
        is_delete: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Fat Boy",
        brand_id: 12,
        year: 2024,
        engine_type: "V-Twin",
        fuel_type: "Petrol",
        transmission: "Manual",
        color_options: JSON.stringify(["Black", "Silver", "Gold"]),
        description:
          "A heavyweight cruiser with iconic styling, a powerful engine, and a comfortable ride for long distances.",
        status: "active",
        is_delete: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Road King",
        brand_id: 12,
        year: 2024,
        engine_type: "V-Twin",
        fuel_type: "Petrol",
        transmission: "Manual",
        color_options: JSON.stringify(["Black", "Silver", "Red"]),
        description:
          "A touring motorcycle with classic styling, built for long journeys with comfortable ergonomics and advanced features.",
        status: "active",
        is_delete: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },

  async down(queryInterface, Sequelize) {
    return await queryInterface.bulkDelete("modells", null, {});
  },
};
