"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert("cities", [
      // Andhra Pradesh Cities
      {
        name: "Visakhapatnam",
        imp: false,
        icon: "",
        state_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Vijayawada",
        imp: false,
        icon: "",
        state_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Guntur",
        imp: false,
        icon: "",
        state_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Tirupati",
        imp: false,
        icon: "",
        state_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Kurnool",
        imp: false,
        icon: "",
        state_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Rajahmundry",
        imp: false,
        icon: "",
        state_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Nellore",
        imp: false,
        icon: "",
        state_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Anantapur",
        imp: false,
        icon: "",
        state_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // Arunachal Pradesh Cities
      {
        name: "Itanagar",
        imp: false,
        icon: "",
        state_id: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Tawang",
        imp: false,
        icon: "",
        state_id: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Naharlagun",
        imp: false,
        icon: "",
        state_id: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Ziro",
        imp: false,
        icon: "",
        state_id: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Pasighat",
        imp: false,
        icon: "",
        state_id: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Aalo",
        imp: false,
        icon: "",
        state_id: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Bomdila",
        imp: false,
        icon: "",
        state_id: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Tezpur",
        imp: false,
        icon: "",
        state_id: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Seppa",
        imp: false,
        icon: "",
        state_id: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Yangtse",
        imp: false,
        icon: "",
        state_id: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // Assam Cities
      {
        name: "Guwahati",
        imp: false,
        icon: "",
        state_id: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Dibrugarh",
        imp: false,
        icon: "",
        state_id: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Jorhat",
        imp: false,
        icon: "",
        state_id: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Nagaon",
        imp: false,
        icon: "",
        state_id: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Silchar",
        imp: false,
        icon: "",
        state_id: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Tinsukia",
        imp: false,
        icon: "",
        state_id: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Tezpur",
        imp: false,
        icon: "",
        state_id: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Sivasagar",
        imp: false,
        icon: "",
        state_id: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Bongaigaon",
        imp: false,
        icon: "",
        state_id: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Barpeta",
        imp: false,
        icon: "",
        state_id: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Karimganj",
        imp: false,
        icon: "",
        state_id: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Golaghat",
        imp: false,
        icon: "",
        state_id: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Nalbari",
        imp: false,
        icon: "",
        state_id: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Haflong",
        imp: false,
        icon: "",
        state_id: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Majuli",
        imp: false,
        icon: "",
        state_id: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // Bihar Cities
      {
        name: "Patna",
        imp: false,
        icon: "",
        state_id: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Gaya",
        imp: false,
        icon: "",
        state_id: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Bhagalpur",
        imp: false,
        icon: "",
        state_id: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Muzaffarpur",
        imp: false,
        icon: "",
        state_id: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Purnia",
        imp: false,
        icon: "",
        state_id: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Darbhanga",
        imp: false,
        icon: "",
        state_id: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Munger",
        imp: false,
        icon: "",
        state_id: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Bettiah",
        imp: false,
        icon: "",
        state_id: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Sasaram",
        imp: false,
        icon: "",
        state_id: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Chapra",
        imp: false,
        icon: "",
        state_id: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Arrah",
        imp: false,
        icon: "",
        state_id: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Nalanda",
        imp: false,
        icon: "",
        state_id: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Kishanganj",
        imp: false,
        icon: "",
        state_id: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Buxar",
        imp: false,
        icon: "",
        state_id: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Jamui",
        imp: false,
        icon: "",
        state_id: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // Chhattisgarh Cities
      {
        name: "Raipur",
        imp: false,
        icon: "",
        state_id: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Bilaspur",
        imp: false,
        icon: "",
        state_id: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Durg",
        imp: false,
        icon: "",
        state_id: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Korba",
        imp: false,
        icon: "",
        state_id: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Raigarh",
        imp: false,
        icon: "",
        state_id: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Jagdalpur",
        imp: false,
        icon: "",
        state_id: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Rajnandgaon",
        imp: false,
        icon: "",
        state_id: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Ambikapur",
        imp: false,
        icon: "",
        state_id: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Dhamtari",
        imp: false,
        icon: "",
        state_id: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Korea",
        imp: false,
        icon: "",
        state_id: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Bilaspur",
        imp: false,
        icon: "",
        state_id: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Surguja",
        imp: false,
        icon: "",
        state_id: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Mungeli",
        imp: false,
        icon: "",
        state_id: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Janjgir",
        imp: false,
        icon: "",
        state_id: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Bemetara",
        imp: false,
        icon: "",
        state_id: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // Goa Cities
      {
        name: "Panaji",
        imp: false,
        icon: "",
        state_id: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Vasco da Gama",
        imp: false,
        icon: "",
        state_id: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Margao",
        imp: false,
        icon: "",
        state_id: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Mapusa",
        imp: false,
        icon: "",
        state_id: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Ponda",
        imp: false,
        icon: "",
        state_id: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Cortalim",
        imp: false,
        icon: "",
        state_id: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Bicholim",
        imp: false,
        icon: "",
        state_id: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Quepem",
        imp: false,
        icon: "",
        state_id: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // Gujarat Cities
      {
        name: "Ahmedabad",
        imp: true,
        icon: "ahmedabad_logo.jpeg",
        state_id: 7,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Surat",
        imp: false,
        icon: "",
        state_id: 7,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Vadodara",
        imp: false,
        icon: "",
        state_id: 7,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Rajkot",
        imp: false,
        icon: "",
        state_id: 7,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Bhavnagar",
        imp: false,
        icon: "",
        state_id: 7,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Junagadh",
        imp: false,
        icon: "",
        state_id: 7,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Nadiad",
        imp: false,
        icon: "",
        state_id: 7,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Gandhinagar",
        imp: false,
        icon: "",
        state_id: 7,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Anand",
        imp: false,
        icon: "",
        state_id: 7,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Morbi",
        imp: false,
        icon: "",
        state_id: 7,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Mehsana",
        imp: false,
        icon: "",
        state_id: 7,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // Haryana Cities
      {
        name: "Gurugram",
        imp: true,
        icon: "gurugram_logo.jpeg",
        state_id: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Faridabad",
        imp: false,
        icon: "",
        state_id: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Hisar",
        imp: false,
        icon: "",
        state_id: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Rohtak",
        imp: false,
        icon: "",
        state_id: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Ambala",
        imp: false,
        icon: "",
        state_id: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Karnal",
        imp: false,
        icon: "",
        state_id: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Panipat",
        imp: false,
        icon: "",
        state_id: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Sonipat",
        imp: false,
        icon: "",
        state_id: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Yamunanagar",
        imp: false,
        icon: "",
        state_id: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Fatehabad",
        imp: false,
        icon: "",
        state_id: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // Himachal Pradesh Cities
      {
        name: "Shimla",
        imp: false,
        icon: "",
        state_id: 9,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Kullu",
        imp: false,
        icon: "",
        state_id: 9,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Mandi",
        imp: false,
        icon: "",
        state_id: 9,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Kangra",
        imp: false,
        icon: "",
        state_id: 9,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Solan",
        imp: false,
        icon: "",
        state_id: 9,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Hamirpur",
        imp: false,
        icon: "",
        state_id: 9,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Una",
        imp: false,
        icon: "",
        state_id: 9,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Bilaspur",
        imp: false,
        icon: "",
        state_id: 9,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // Jharkhand Cities
      {
        name: "Ranchi",
        imp: false,
        icon: "",
        state_id: 10,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Jamshedpur",
        imp: false,
        icon: "",
        state_id: 10,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Dhanbad",
        imp: false,
        icon: "",
        state_id: 10,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Bokaro Steel City",
        imp: false,
        icon: "",
        state_id: 10,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Giridih",
        imp: false,
        icon: "",
        state_id: 10,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Deoghar",
        imp: false,
        icon: "",
        state_id: 10,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Hazaribagh",
        imp: false,
        icon: "",
        state_id: 10,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Ramgarh",
        imp: false,
        icon: "",
        state_id: 10,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Chaibasa",
        imp: false,
        icon: "",
        state_id: 10,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Koderma",
        imp: false,
        icon: "",
        state_id: 10,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Saraikela",
        imp: false,
        icon: "",
        state_id: 10,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Sahebganj",
        imp: false,
        icon: "",
        state_id: 10,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Simdega",
        imp: false,
        icon: "",
        state_id: 10,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Pakur",
        imp: false,
        icon: "",
        state_id: 10,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Latehar",
        imp: false,
        icon: "",
        state_id: 10,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // Karnataka Cities
      {
        name: "Bengaluru",
        imp: true,
        icon: "banglore_logo.jpeg",
        state_id: 11,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Mysuru",
        imp: false,
        icon: "",
        state_id: 11,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Hubballi",
        imp: false,
        icon: "",
        state_id: 11,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Mangaluru",
        imp: false,
        icon: "",
        state_id: 11,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Belagavi",
        imp: false,
        icon: "",
        state_id: 11,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Davangere",
        imp: false,
        icon: "",
        state_id: 11,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Ballari",
        imp: false,
        icon: "",
        state_id: 11,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Tumakuru",
        imp: false,
        icon: "",
        state_id: 11,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Shimoga",
        imp: false,
        icon: "",
        state_id: 11,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Chitradurga",
        imp: false,
        icon: "",
        state_id: 11,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Hospet",
        imp: false,
        icon: "",
        state_id: 11,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Bijapur",
        imp: false,
        icon: "",
        state_id: 11,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Raichur",
        imp: false,
        icon: "",
        state_id: 11,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Kolar",
        imp: false,
        icon: "",
        state_id: 11,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Udupi",
        imp: false,
        icon: "",
        state_id: 11,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // Kerala Cities
      {
        name: "Thiruvananthapuram",
        imp: false,
        icon: "",
        state_id: 12,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Kochi",
        imp: false,
        icon: "",
        state_id: 12,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Kozhikode",
        imp: false,
        icon: "",
        state_id: 12,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Thrissur",
        imp: false,
        icon: "",
        state_id: 12,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Kollam",
        imp: false,
        icon: "",
        state_id: 12,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Alappuzha",
        imp: false,
        icon: "",
        state_id: 12,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Malappuram",
        imp: false,
        icon: "",
        state_id: 12,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Kannur",
        imp: false,
        icon: "",
        state_id: 12,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Pathanamthitta",
        imp: false,
        icon: "",
        state_id: 12,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Idukki",
        imp: false,
        icon: "",
        state_id: 12,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Palakkad",
        imp: false,
        icon: "",
        state_id: 12,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Kottayam",
        imp: false,
        icon: "",
        state_id: 12,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Wayanad",
        imp: false,
        icon: "",
        state_id: 12,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Pernem",
        imp: false,
        icon: "",
        state_id: 12,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Attingal",
        imp: false,
        icon: "",
        state_id: 12,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // Madhya Pradesh Cities
      {
        name: "Bhopal",
        imp: false,
        icon: "",
        state_id: 13,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Indore",
        imp: false,
        icon: "",
        state_id: 13,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Gwalior",
        imp: false,
        icon: "",
        state_id: 13,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Jabalpur",
        imp: false,
        icon: "",
        state_id: 13,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Ujjain",
        imp: false,
        icon: "",
        state_id: 13,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Sagar",
        imp: false,
        icon: "",
        state_id: 13,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Dewas",
        imp: false,
        icon: "",
        state_id: 13,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Rewa",
        imp: false,
        icon: "",
        state_id: 13,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Burhanpur",
        imp: false,
        icon: "",
        state_id: 13,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Satna",
        imp: false,
        icon: "",
        state_id: 13,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Chhindwara",
        imp: false,
        icon: "",
        state_id: 13,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Khandwa",
        imp: false,
        icon: "",
        state_id: 13,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Shivpuri",
        imp: false,
        icon: "",
        state_id: 13,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Mandsaur",
        imp: false,
        icon: "",
        state_id: 13,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Ratlam",
        imp: false,
        icon: "",
        state_id: 13,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // Maharashtra Cities
      {
        name: "Mumbai",
        imp: true,
        icon: "mumbai_logo.jpeg",
        state_id: 14,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Pune",
        imp: true,
        icon: "pune_logo.jpeg",
        state_id: 14,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Nagpur",
        imp: false,
        icon: "",
        state_id: 14,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Nashik",
        imp: false,
        icon: "",
        state_id: 14,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Aurangabad",
        imp: false,
        icon: "",
        state_id: 14,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Thane",
        imp: false,
        icon: "",
        state_id: 14,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Kalyan",
        imp: false,
        icon: "",
        state_id: 14,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Solapur",
        imp: false,
        icon: "",
        state_id: 14,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Satara",
        imp: false,
        icon: "",
        state_id: 14,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Chandrapur",
        imp: false,
        icon: "",
        state_id: 14,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Kolhapur",
        imp: false,
        icon: "",
        state_id: 14,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Jalgaon",
        imp: false,
        icon: "",
        state_id: 14,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Amravati",
        imp: false,
        icon: "",
        state_id: 14,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Bhiwandi",
        imp: false,
        icon: "",
        state_id: 14,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Ulhasnagar",
        imp: false,
        icon: "",
        state_id: 14,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // Manipur Cities
      {
        name: "Thoubal",
        imp: false,
        icon: "",
        state_id: 15,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Kangpokpi",
        imp: false,
        icon: "",
        state_id: 15,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Bishnupur",
        imp: false,
        icon: "",
        state_id: 15,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Churachandpur",
        imp: false,
        icon: "",
        state_id: 15,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Chandel",
        imp: false,
        icon: "",
        state_id: 15,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Ukhrul",
        imp: false,
        icon: "",
        state_id: 15,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Senapati",
        imp: false,
        icon: "",
        state_id: 15,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Tamenglong",
        imp: false,
        icon: "",
        state_id: 15,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Tengnoupal",
        imp: false,
        icon: "",
        state_id: 15,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // Meghalaya Cities
      {
        name: "Shillong",
        imp: false,
        icon: "",
        state_id: 16,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Tura",
        imp: false,
        icon: "",
        state_id: 16,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Nongstoin",
        imp: false,
        icon: "",
        state_id: 16,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Jowai",
        imp: false,
        icon: "",
        state_id: 16,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Williamnagar",
        imp: false,
        icon: "",
        state_id: 16,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Baghmara",
        imp: false,
        icon: "",
        state_id: 16,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Resubelpara",
        imp: false,
        icon: "",
        state_id: 16,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Mawlai",
        imp: false,
        icon: "",
        state_id: 16,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Amlarem",
        imp: false,
        icon: "",
        state_id: 16,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Nartiang",
        imp: false,
        icon: "",
        state_id: 16,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // Mizoram Cities
      {
        name: "Aizawl",
        imp: false,
        icon: "",
        state_id: 17,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Lunglei",
        imp: false,
        icon: "",
        state_id: 17,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Champhai",
        imp: false,
        icon: "",
        state_id: 17,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Siaha",
        imp: false,
        icon: "",
        state_id: 17,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Kolasib",
        imp: false,
        icon: "",
        state_id: 17,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Serchhip",
        imp: false,
        icon: "",
        state_id: 17,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Mamit",
        imp: false,
        icon: "",
        state_id: 17,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Lawngtlai",
        imp: false,
        icon: "",
        state_id: 17,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Hnahthial",
        imp: false,
        icon: "",
        state_id: 17,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Khawzawl",
        imp: false,
        icon: "",
        state_id: 17,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // Nagaland Cities
      {
        name: "Kohima",
        imp: false,
        icon: "",
        state_id: 18,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Dimapur",
        imp: false,
        icon: "",
        state_id: 18,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Mokokchung",
        imp: false,
        icon: "",
        state_id: 18,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Mon",
        imp: false,
        icon: "",
        state_id: 18,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Zunheboto",
        imp: false,
        icon: "",
        state_id: 18,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Wokha",
        imp: false,
        icon: "",
        state_id: 18,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Peren",
        imp: false,
        icon: "",
        state_id: 18,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Tuensang",
        imp: false,
        icon: "",
        state_id: 18,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Longleng",
        imp: false,
        icon: "",
        state_id: 18,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Kiphire",
        imp: false,
        icon: "",
        state_id: 18,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // Odisha Cities
      {
        name: "Bhubaneswar",
        imp: false,
        icon: "",
        state_id: 19,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Cuttack",
        imp: false,
        icon: "",
        state_id: 19,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Berhampur",
        imp: false,
        icon: "",
        state_id: 19,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Rourkela",
        imp: false,
        icon: "",
        state_id: 19,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Sambalpur",
        imp: false,
        icon: "",
        state_id: 19,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Balasore",
        imp: false,
        icon: "",
        state_id: 19,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Koraput",
        imp: false,
        icon: "",
        state_id: 19,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Baripada",
        imp: false,
        icon: "",
        state_id: 19,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Angul",
        imp: false,
        icon: "",
        state_id: 19,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Puri",
        imp: false,
        icon: "",
        state_id: 19,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // Punjab Cities
      {
        name: "Chandigarh",
        imp: false,
        icon: "",
        state_id: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Amritsar",
        imp: false,
        icon: "",
        state_id: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Ludhiana",
        imp: false,
        icon: "",
        state_id: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Jalandhar",
        imp: false,
        icon: "",
        state_id: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Patiala",
        imp: false,
        icon: "",
        state_id: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Mohali",
        imp: false,
        icon: "",
        state_id: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Bathinda",
        imp: false,
        icon: "",
        state_id: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Hoshiarpur",
        imp: false,
        icon: "",
        state_id: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Ferozepur",
        imp: false,
        icon: "",
        state_id: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Sri Muktsar Sahib",
        imp: false,
        icon: "",
        state_id: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // Rajasthan Cities
      {
        name: "Jaipur",
        imp: true,
        icon: "jaipur_logo.jpeg",
        state_id: 21,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Jodhpur",
        imp: false,
        icon: "",
        state_id: 21,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Udaipur",
        imp: false,
        icon: "",
        state_id: 21,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Kota",
        imp: false,
        icon: "",
        state_id: 21,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Ajmer",
        imp: false,
        icon: "",
        state_id: 21,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Bikaner",
        imp: false,
        icon: "",
        state_id: 21,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Alwar",
        imp: false,
        icon: "",
        state_id: 21,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Sikar",
        imp: false,
        icon: "",
        state_id: 21,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Tonk",
        imp: false,
        icon: "",
        state_id: 21,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Pali",
        imp: false,
        icon: "",
        state_id: 21,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // Sikkim Cities
      {
        name: "Gangtok",
        imp: false,
        icon: "",
        state_id: 22,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Namchi",
        imp: false,
        icon: "",
        state_id: 22,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Mangan",
        imp: false,
        icon: "",
        state_id: 22,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Rangpo",
        imp: false,
        icon: "",
        state_id: 22,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Jorethang",
        imp: false,
        icon: "",
        state_id: 22,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Singtam",
        imp: false,
        icon: "",
        state_id: 22,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // Tamil Nadu Cities
      {
        name: "Chennai",
        imp: true,
        icon: "chennai_logo.jpeg",
        state_id: 23,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Coimbatore",
        imp: false,
        icon: "",
        state_id: 23,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Madurai",
        imp: false,
        icon: "",
        state_id: 23,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Tiruchirappalli",
        imp: false,
        icon: "",
        state_id: 23,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Salem",
        imp: false,
        icon: "",
        state_id: 23,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Erode",
        imp: false,
        icon: "",
        state_id: 23,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Tirunelveli",
        imp: false,
        icon: "",
        state_id: 23,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Vellore",
        imp: false,
        icon: "",
        state_id: 23,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Thoothukudi",
        imp: false,
        icon: "",
        state_id: 23,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Dindigul",
        imp: false,
        icon: "",
        state_id: 23,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Chidambaram",
        imp: false,
        icon: "",
        state_id: 23,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Kanchipuram",
        imp: false,
        icon: "",
        state_id: 23,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Kumbakonam",
        imp: false,
        icon: "",
        state_id: 23,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Karur",
        imp: false,
        icon: "",
        state_id: 23,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Nagercoil",
        imp: false,
        icon: "",
        state_id: 23,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // Telangana Cities
      {
        name: "Hyderabad",
        imp: false,
        icon: "",
        state_id: 24,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Warangal",
        imp: false,
        icon: "",
        state_id: 24,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Khammam",
        imp: false,
        icon: "",
        state_id: 24,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Nizamabad",
        imp: false,
        icon: "",
        state_id: 24,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Karimnagar",
        imp: false,
        icon: "",
        state_id: 24,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Ramagundam",
        imp: false,
        icon: "",
        state_id: 24,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Sircilla",
        imp: false,
        icon: "",
        state_id: 24,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Mahbubnagar",
        imp: false,
        icon: "",
        state_id: 24,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Adilabad",
        imp: false,
        icon: "",
        state_id: 24,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Jagtial",
        imp: false,
        icon: "",
        state_id: 24,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // Uttar Pradesh Cities
      {
        name: "Noida",
        imp: true,
        icon: "noida_logo.jpeg",
        state_id: 25,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Lucknow",
        imp: false,
        icon: "",
        state_id: 25,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Kanpur",
        imp: false,
        icon: "",
        state_id: 25,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Agra",
        imp: false,
        icon: "",
        state_id: 25,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Varanasi",
        imp: false,
        icon: "",
        state_id: 25,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Allahabad",
        imp: false,
        icon: "",
        state_id: 25,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Bareilly",
        imp: false,
        icon: "",
        state_id: 25,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Gorakhpur",
        imp: false,
        icon: "",
        state_id: 25,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Meerut",
        imp: false,
        icon: "",
        state_id: 25,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Aligarh",
        imp: false,
        icon: "",
        state_id: 25,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Mathura",
        imp: false,
        icon: "",
        state_id: 25,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Moradabad",
        imp: false,
        icon: "",
        state_id: 25,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Muzaffarnagar",
        imp: false,
        icon: "",
        state_id: 25,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Saharanpur",
        imp: false,
        icon: "",
        state_id: 25,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Firozabad",
        imp: false,
        icon: "",
        state_id: 25,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Shahjahanpur",
        imp: false,
        icon: "",
        state_id: 25,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // Uttarakhand Cities
      {
        name: "Dehradun",
        imp: false,
        icon: "",
        state_id: 26,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Haridwar",
        imp: false,
        icon: "",
        state_id: 26,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Nainital",
        imp: false,
        icon: "",
        state_id: 26,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Rishikesh",
        imp: false,
        icon: "",
        state_id: 26,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Roorkee",
        imp: false,
        icon: "",
        state_id: 26,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Haldwani",
        imp: false,
        icon: "",
        state_id: 26,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Udhamsingh Nagar",
        imp: false,
        icon: "",
        state_id: 26,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Almora",
        imp: false,
        icon: "",
        state_id: 26,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Mussoorie",
        imp: false,
        icon: "",
        state_id: 26,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Pauri",
        imp: false,
        icon: "",
        state_id: 26,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // West Bengal Cities
      {
        name: "Kolkata",
        imp: false,
        icon: "",
        state_id: 27,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Howrah",
        imp: false,
        icon: "",
        state_id: 27,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Siliguri",
        imp: false,
        icon: "",
        state_id: 27,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Durgapur",
        imp: false,
        icon: "",
        state_id: 27,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Asansol",
        imp: false,
        icon: "",
        state_id: 27,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Burdwan",
        imp: false,
        icon: "",
        state_id: 27,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Malda",
        imp: false,
        icon: "",
        state_id: 27,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Jalpaiguri",
        imp: false,
        icon: "",
        state_id: 27,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Kharagpur",
        imp: false,
        icon: "",
        state_id: 27,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Medinipur",
        imp: false,
        icon: "",
        state_id: 27,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // Andaman and Nicobar Islands Cities
      {
        name: "Port Blair",
        imp: false,
        icon: "",
        state_id: 28,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Car Nicobar",
        imp: false,
        icon: "",
        state_id: 28,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Mayabunder",
        imp: false,
        icon: "",
        state_id: 28,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Diglipur",
        imp: false,
        icon: "",
        state_id: 28,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Havelock",
        imp: false,
        icon: "",
        state_id: 28,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Neil Island",
        imp: false,
        icon: "",
        state_id: 28,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // Chandigarh Cities
      {
        name: "Chandigarh",
        imp: false,
        icon: "",
        state_id: 29,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // Dadra and Nagar Haveli and Daman and Diu Cities
      {
        name: "Daman",
        imp: false,
        icon: "",
        state_id: 30,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Diu",
        imp: false,
        icon: "",
        state_id: 30,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Silvassa",
        imp: false,
        icon: "",
        state_id: 30,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // Lakshadweep Cities
      {
        name: "Kavaratti",
        imp: false,
        icon: "",
        state_id: 31,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Agatti",
        imp: false,
        icon: "",
        state_id: 31,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Andrott",
        imp: false,
        icon: "",
        state_id: 31,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Minicoy",
        imp: false,
        icon: "",
        state_id: 31,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // Delhi Cities
      {
        name: "New Delhi",
        imp: true,
        icon: "new_delhi_logo.jpeg",
        state_id: 32,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Delhi NCR",
        imp: true,
        icon: "delhi_ncr_logo.jpeg",
        state_id: 32,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Central Delhi",
        imp: false,
        icon: "",
        state_id: 32,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "West Delhi",
        imp: false,
        icon: "",
        state_id: 32,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "South Delhi",
        imp: false,
        icon: "",
        state_id: 32,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "North Delhi",
        imp: false,
        icon: "",
        state_id: 32,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "East Delhi",
        imp: false,
        icon: "",
        state_id: 32,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "North West Delhi",
        imp: false,
        icon: "",
        state_id: 32,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "South West Delhi",
        imp: false,
        icon: "",
        state_id: 32,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Shahdara",
        imp: false,
        icon: "",
        state_id: 32,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Southeast Delhi",
        imp: false,
        icon: "",
        state_id: 32,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // Puducherry Cities
      {
        name: "Puducherry",
        imp: false,
        icon: "",
        state_id: 33,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Karaikal",
        imp: false,
        icon: "",
        state_id: 33,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Mahe",
        imp: false,
        icon: "",
        state_id: 33,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Yanam",
        imp: false,
        icon: "",
        state_id: 33,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // Ladakh Cities
      {
        name: "Leh",
        imp: false,
        icon: "",
        state_id: 34,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Kargil",
        imp: false,
        icon: "",
        state_id: 34,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Nubra",
        imp: false,
        icon: "",
        state_id: 34,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Zanskar",
        imp: false,
        icon: "",
        state_id: 34,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // Jammu & Kashmir Cities
      {
        name: "Srinagar",
        imp: false,
        icon: "",
        state_id: 35,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Jammu",
        imp: false,
        icon: "",
        state_id: 35,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Sopore",
        imp: false,
        icon: "",
        state_id: 35,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Anantnag",
        imp: false,
        icon: "",
        state_id: 35,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Baramulla",
        imp: false,
        icon: "",
        state_id: 35,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Pulwama",
        imp: false,
        icon: "",
        state_id: 35,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Kupwara",
        imp: false,
        icon: "",
        state_id: 35,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Udhampur",
        imp: false,
        icon: "",
        state_id: 35,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Kathua",
        imp: false,
        icon: "",
        state_id: 35,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Rajouri",
        imp: false,
        icon: "",
        state_id: 35,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },

  async down(queryInterface, Sequelize) {
    return await queryInterface.bulkDelete("cities", null, {});
  },
};
